### ISSUE TITLE
Feasibility Report

### ISSUE THREAD

**Issue by akash1997** [akash1997/Solid-Waste-Management-System#1]
The Feasibility report of our project mentioning the various ideas and their feasibility and why was our idea finally chosen.

**Comment by akash1997** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feasibility Report Document](https://trello.com/c/MXQd3Te0/22-feasibility-report-document)

**Comment by DaitTan** [comment]
[Feasibility Report.pdf](https://github.com/akash1997/Solid-Waste-Management-System/files/1347187/Feasibility.Report.pdf)
